version: "3.8"
services:
  frontend-develop:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: agent-development
    volumes:
      - type: bind
        source: ./frontend
        target: /usr/src/app/agent-frontend
        consistency: cached
      - /frontend/node_modules
    ports:
      - "5175:5175"
    depends_on:
      - backend-develop
    command: npm run dev
    profiles:
      - agent-development

  frontend-production:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: agent-production
    ports:
      - "5175:5175"
    depends_on:
      - backend-production
    profiles:
      - agent-production

  backend-develop:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: agent-development
    volumes:
      - type: bind
        source: ./backend
        target: /usr/src/app/agent-backend
        consistency: cached
      - /backend/node_modules
    ports:
      - "5009:5009"
    command: npm run dev
    profiles:
      - agent-development

  backend-production:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: agent-production
    ports:
      - "5009:5009"
    profiles:
      - agent-production
